In [5]:
from __future__ import division, print_function, unicode_literals
import numpy as np 
import matplotlib.pyplot as plt

In [6]:
X = np.array([ [1, 100, 7, 42, 0], [1, 150, 7, 62, 0], [1, 118, 6, 40, 0], [1, 123, 6, 54, 0], [1, 112, 6, 42, 0],
        [1, 99, 6, 56, 0], [1, 124, 7, 51, 1], [1, 150, 6, 32, 0], [1, 342, 10, 42, 1], [1, 300, 9, 14, 1],
        [1, 123, 6, 32, 0], [1, 155, 6, 30, 0], [1, 98, 5, 30, 0], [1, 112, 6, 32, 0], [1, 102, 5, 46, 1],
        [1, 150, 6, 32, 0], [1, 166, 8, 50, 0], [1, 149, 7, 22, 1], [1, 138, 6, 17, 0], [1, 150, 7, 23, 0]]).T
y = np.array([[259, 295, 279, 259, 299, 299, 309, 289, 849, 829, 359, 315, 310, 309, 300, 289, 369, 419, 405, 439]]).T

In [13]:
one = np.ones((X.shape[0],1))
Xbar = X.T
print(Xbar)
A = np.dot(Xbar.T, Xbar)
b = np.dot(Xbar.T, y)
w = np.dot(np.linalg.pinv(A), b)
print('w = ', w)

[[  1 100   7  42   0]
 [  1 150   7  62   0]
 [  1 118   6  40   0]
 [  1 123   6  54   0]
 [  1 112   6  42   0]
 [  1  99   6  56   0]
 [  1 124   7  51   1]
 [  1 150   6  32   0]
 [  1 342  10  42   1]
 [  1 300   9  14   1]
 [  1 123   6  32   0]
 [  1 155   6  30   0]
 [  1  98   5  30   0]
 [  1 112   6  32   0]
 [  1 102   5  46   1]
 [  1 150   6  32   0]
 [  1 166   8  50   0]
 [  1 149   7  22   1]
 [  1 138   6  17   0]
 [  1 150   7  23   0]]
w =  [[46.57608884]
 [ 1.80877941]
 [20.51647902]
 [-2.38581452]
 [54.29644678]]


In [16]:
s1=float(input("Nhap dien tich (m2):  "))
s2=float(input("Nhap vao so phong:  "))
s3=float(input("Tuoi can nha:  "))
s4=float(input("So nha tam:  "))
money=w[0][0]*s1+w[1][0]*s2+w[2][0]*s3+w[3][0]*s4
print("Predict home price: %.2f" %(money))

Nhap dien tich (m2):  15
Nhap vao so phong:  2
Tuoi can nha:  2
So nha tam:  2
Predict home price: 738.52
